swagger: "2.0"
info:
  title: Phase 2 - Transaction
  description: Phase 2 - Transaction
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - https
  - http
paths:
  /transactions/:
    parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
    get:
      security:
        - Bearer: []
      tags:
        - Transactions for specified month
      summary: An authenticated user can retrieve all transactions for a specified month
      description: >-
        This API allows an authenticated user to retrieve all transactions for a specified month.
      operationId: getTransactions
      parameters:
        - in: query
          name: month
          required: false
          type: string
          description: The month to retrieve transactions for. If not specified, the current month is used.
      responses:
        "200":
          description: Successfully retrieved user's transactions for the specified month
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error

  /transactions/{transactionId}:
    parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: transactionId
        required: true
        type: integer
        description: Transaction unique id
    get:
      tags:
        - Transaction Management
      summary: Get the details of a specific transaction.
      operationId: getTransaction
      responses:
        "200":
          description: Successfully retrieved transaction details
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid input
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    patch:
      tags:
        - Transaction Management
      summary: Update a specific transaction information.
      operationId: updateTransaction
      parameters:
        - name: JsonPatch
          in: body
          required: true
          schema:
            $ref: "#/definitions/TransactionUpdate"
      responses:
        "200":
          description: Successfully updated transaction
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid input
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    delete:
      tags:
        - Transaction Management
      summary: Delete a specific transaction.
      operationId: deleteTransaction
      responses:
        "204":
          description: Successfully deleted transaction
        "400":
          description: Invalid input
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Transaction:
    type: object
    properties:
      id:
        type: integer
        description: The unique identifier for the transaction.
      amount:
        type: number
        description: The amount of the transaction.
      date:
        type: string
        format: date-time
        description: The date and time the transaction was created.
      type:
        type: string
        description: The type of the transaction (e.g., "debit", "credit")
      description:
        type: string
        description: A description of the transaction (optional)
  TransactionUpdate:
    type: object
    properties:
      amount:
        type: number
        description: The amount of the transaction.
      date:
        type: string
        format: date-time
        description: The date and time the transaction was created.
      type:
        type: string
        description: The type of the transaction (e.g., "debit", "credit")
      description:
        type: string
        description: A description of the transaction (optional)
